### ISSUE TITLE
Please merge p8-platfrom fix to Jarvis branch

### ISSUE THREAD

**Issue by sagiben** [kodi-pvr/pvr.wmc#34]
As you know kodi Jarvis uses p8-platform instead of platform lib (due to a name change)
this fix was made only in master branch.
Can it be merged into Jarvis branch ?

the relevant commit is this merge of pull request #30 
https://github.com/kodi-pvr/pvr.wmc/commit/ae315550694c5334b817c76fe05f74e509273631

Thank you,
 Sagi.

**Comment by MartijnKaijser** [comment]
No jarvis branch has this
